Dev
MaryGoo/Sprint_3 pull request #1
Opened 2021-11-28 04:46 UTC by MaryGoo

Sprint_3

2021-11-28 04:47 UTC, MaryGoo commented
Sprint_3

2021-11-29 17:48 UTC, egorvas requested changes

2021-11-29 17:48 UTC, egorvas commented on .allure/allure-2.15.0/bin/allure
> +#!/bin/sh
Папку .allure нужно убирать в .gitignore 
Она не нужна в проекте

2021-11-29 17:48 UTC, egorvas commented on pom.xml
> +        <!--        <dependency>-->
Если что-то не используешь, то перед пул реквестом стоит это удалять, даже из комментариев

2021-11-29 17:48 UTC, egorvas commented on src/main/java/ru/praktikum_services/qa_scooter/client/CourierClient.java
> +                .log().body();
Логировать респонсы прикольно, это сильно помогает в дебаге тестов. Но я рекомендую также логировать и реквесты, чтобы понимать к чему относится респонс.

2021-11-29 17:48 UTC, egorvas commented on src/main/java/ru/praktikum_services/qa_scooter/client/OrderClient.java
> +                .body("{\"id\":"+orderId+"}")
Я крайне рекомендую делать body JSON не через строки, а через специальные генераторы JSON. Это сильно упрощает код и делает его более красивым. К сожалению в JAVA нет стандартного удобного способа делать это, советую подключить модуль json или gson создавать JSON через него.

2021-11-29 17:48 UTC, egorvas commented on src/main/java/ru/praktikum_services/qa_scooter/models/Courier.java
> +        String[] listFirstName = {"Евгения", "Екатерина", "Елена", "Епистима",
То что ты создала массив с именами по сути лишняя работа. Можно было просто генерить случайную строку. Но есть еще более удобный вариант использовать специальные модуля для генерации данных. Например Faker, вот тут описаны примеры как его использовать https://medium.com/techwasti/java-faker-library-to-generate-fake-data-229df7595211 С его помощью можно генерить тестовые данные без хардкода.

2021-11-29 17:48 UTC, egorvas commented on src/main/java/ru/praktikum_services/qa_scooter/models/Order.java
> +    public static String setAddress() {
Аналогично моему комментарию выше, все эти данные можно генерить с помощью специальных инструментов.

2021-11-29 17:48 UTC, egorvas commented on pom.xml
> +            <groupId>com.fasterxml.jackson.core</groupId>
Ты используешь и  jackson и gson? Тебе точно нужны оба этих модуля одновременно?

2021-11-29 17:48 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/CourierLogin/loginWithWrongFieldsTest.java
> +        replace(courier,fieldName,"someWrongValue");
Я конечно понимаю, что так можно делать, но мне такой путь генерации данных для теста ну совсем не нравится. Мне кажется параметризация тут лишняя. Слишком много обвязки, для того чтобы сделать пару довольно простых тестов.

2021-11-29 17:48 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/CourierLogin/loginTest.java
> +        assertThat("Courier ID is incorrect", courierId, is(not(0)));
ты уверена что это хорошая проверка? Что будет если courierId вообще не будет определен?

2021-11-29 17:48 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/CourierDelete/DeleteCourierWithWrongId.java
> +        courierId = Integer.parseInt(RandomStringUtils.random(8,"123456789"));
Ты этот код используешь в нескольких местах, его точно можно вынести в отдельную функцию. А лучше создавать обхект курьера прямо с ним.

2021-11-29 17:48 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/CourierCreate/CreateSameCourierTest.java
> +        courier_2 = Courier.getRandom();
Пожалуйста используй единый стандарт нейминга переменных, в java это как правило camelCase

2021-11-29 17:48 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/CourierCreate/CreateSameCourierTest.java
> +    Courier courier_1;
Здесь можно было обойтись без before и соответственно сделать эту и следующую переменную локальными.

2021-11-29 17:48 UTC, egorvas commented on src/main/java/ru/praktikum_services/qa_scooter/utilities/Utilities.java
> +    public static void replace(Courier courier, String fieldName, String newValue){
Я настоятельно рекомендую удалить этот класс и не использовать. Если уж тебе так сильно важно иметь его внеси в модель курьера, но мне кажется лучше вообще без этого replace обойтись.

2021-11-29 17:48 UTC, egorvas commented on src/main/java/ru/praktikum_services/qa_scooter/utilities/Orders.java
> +    public static  List<OrderFromDB> generateOrderFromDBList(List<Object> orderFromDBListObj) {
Я почти на 100% уверен, что это место можно сделать проще. Мне кажется ты тут сама себя перемеудрила. Попробуй поменять типы данных.

2021-11-29 17:48 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/OrdersGetList/OrdersListGet.java
> +        orderFromDBList = generateOrderFromDBList(orderFromDBListObj);
Можешь пояснить зачем тут вообще приведение к классу OrderFromDB? Почему нельзя было исходный список orderFromDBListObj проверять?

2021-12-01 02:20 UTC, MaryGoo commented on src/main/java/ru/praktikum_services/qa_scooter/utilities/Utilities.java
> +    public static void replace(Courier courier, String fieldName, String newValue){
Utilities удалила.

про: .login(CourierCredentials.from(courierFirst))
я логинюсь под данными клиента. в любом случае связь будет между CourierCredentials и Courier будет.
я могу создать новый метод в CourierCredentials по типу:    
public void create(Courier courier){
        this.login=courier.login;
        this.password=courier.password;
    }
private CourierCredentials courierCredentials; //в классе тестов создать переменную 
courierCredentials = new CourierCredentials(); //инициализировать
 и потом вместо CourierCredentials.from(courierFirst) написать: courierCredentials.create(courier);

думаю CourierCredentials.from(courierFirst) более лаконично так как в коде теста не создаётся отдельная переменная.

2021-12-01 02:50 UTC, MaryGoo commented on src/main/java/ru/praktikum_services/qa_scooter/utilities/Orders.java
> +    public static  List<OrderFromDB> generateOrderFromDBList(List<Object> orderFromDBListObj) {
к сожалению мое отсутствие опыта не дало мне возможность найти более изящное решение. возможно что то усложнено. на это решение у потратила 4 часа) ну и сейчас сроки повторной сдачи поджимают) 
сейчас уточнила у наставника (Ульяна) как можно было сделать аналогичную проверку более простой.

2021-12-01 02:50 UTC, MaryGoo commented on src/test/java/ru/praktikum_services/qa_scooter/OrdersGetList/OrdersListGet.java
> +        orderFromDBList = generateOrderFromDBList(orderFromDBListObj);
1. orderFromDBList.forEach(orderFromDB -> assertThat(orderFromDB.id, is(not(0))));
в исходном списке orderFromDBListObj нет поля id, после приведения типов я могу с уверенностью в 100% проверить что получила список заказав и каждый заказ имеет id , можно вообще добавить проверку на каждое поле заказа из ответа. 
2. assertThat(orderFromDBList.size(),equalTo(limit)); - эту проверку можно выполнить и со списком orderFromDBListObj

2021-12-04 10:55 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/order/create/OrdersCreateTest.java
> +    public OrdersCreateTest(String color_1, String color_2) {
Почему бы параметром просто не иметь массив?

2021-12-04 10:55 UTC, egorvas commented on src/test/java/ru/praktikum_services/qa_scooter/order/create/OrdersCreateTest.java
> +    public OrdersCreateTest(String color_1, String color_2) {
Никогда не используй цифры в названии переменных. Да и нижние подчеркивания тоже. В java принято использовать camelCase

2021-12-06 17:52 UTC, merged